# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitScope < Formula
  desc "A fast TUI to see the status of all git repositories"
  homepage "https://github.com/Bharath-code/git-scope"
  version "1.3.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Bharath-code/git-scope/releases/download/v1.3.1/git-scope_1.3.1_darwin_amd64.tar.gz"
      sha256 "68ea5287d4d2156821d41fbfdefbd9758e6e3df1a139620455cce7616a64a7e2"

      def install
        bin.install "git-scope"
      end
    end
    on_arm do
      url "https://github.com/Bharath-code/git-scope/releases/download/v1.3.1/git-scope_1.3.1_darwin_arm64.tar.gz"
      sha256 "04622bac724fbd97d8bbdcced63574e8e3ab5223bc17394432743cca52788d92"

      def install
        bin.install "git-scope"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Bharath-code/git-scope/releases/download/v1.3.1/git-scope_1.3.1_linux_amd64.tar.gz"
        sha256 "c8e3ea67245e3013d708e6734c1fdd0ff2df414553053238d74747e27d740575"

        def install
          bin.install "git-scope"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Bharath-code/git-scope/releases/download/v1.3.1/git-scope_1.3.1_linux_arm64.tar.gz"
        sha256 "8c0ed5b1d6589935fec899d0aaef62b3df43c47f27536de6306badd80c4abb8e"

        def install
          bin.install "git-scope"
        end
      end
    end
  end

  test do
    system "#{bin}/git-scope", "help"
  end
end
