# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitScope < Formula
  desc "A fast TUI to see the status of all git repositories"
  homepage "https://github.com/Bharath-code/git-scope"
  version "1.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Bharath-code/git-scope/releases/download/v1.2.1/git-scope_1.2.1_darwin_amd64.tar.gz"
      sha256 "b7f8dabd957ebee93f4e79f098aec6ae91550505595e8d15e35ecf22afe602c7"

      def install
        bin.install "git-scope"
      end
    end
    on_arm do
      url "https://github.com/Bharath-code/git-scope/releases/download/v1.2.1/git-scope_1.2.1_darwin_arm64.tar.gz"
      sha256 "e17ea234862e295c54137d4b3ec10d27a0402305d577435732e1e445e8f1ddd2"

      def install
        bin.install "git-scope"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Bharath-code/git-scope/releases/download/v1.2.1/git-scope_1.2.1_linux_amd64.tar.gz"
        sha256 "dbb68a63358d807c9c93ac90a8a895aec23a0a061aa40f9d3d9718905af1992a"

        def install
          bin.install "git-scope"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Bharath-code/git-scope/releases/download/v1.2.1/git-scope_1.2.1_linux_arm64.tar.gz"
        sha256 "5837dad01f45676aec2742199d429ba98531f87c666241d2df479f83fb4a0dbc"

        def install
          bin.install "git-scope"
        end
      end
    end
  end

  test do
    system "#{bin}/git-scope", "help"
  end
end
